### ISSUE TITLE
Remove posix dependency from cv

### ISSUE THREAD

**Issue by ninareyes** [civicrm/cv#116]
The posix php extension has been considered a security risk for several months now (see [here](https://www.php.net/manual/en/intro.posix.php) and [here](https://gist.github.com/mccabe615/b0907514d34b2de088c4996933ea1720) for more information). As a result, it is disabled by default by some Linux hosts, including Pantheon.

cv still requires posix but keeping the extension enabled poses a security risk. Running cv with posix disabled results in the following error: `Call to undefined function Civi\Cv\Command\posix_getuid()`

Are there plans to address and remove this dependency from cv?

**Comment by kelizoliva** [comment]
What is the likelihood that this dependency will be relaxed in the near future?

**Comment by totten** [comment]
I'm gonna close the issue. I believe the original error was previously fixed by 8a9c64af.

> I would say +1 for relaxing the dependency opportunistically.

Reiterating this -- broadly, POSIX seems important to what `cv` does, so I'm not going to go on an open-ended mission to "search+replace" anything just because it smells POSIX-like. But when someone has a specific problem (like `cv upgrade:db` fails due to `posix_getuid()`), then that's patchwelcome.
