### ISSUE TITLE
Shell completion

### ISSUE THREAD

**Issue by chriscroome** [civicrm/cv#164]
Is there a shell completion (I'm specifically interested in a Bash one) available for `cv` anywhere? 

If not would adding a method to generate the required files be something that could be considered as a feature request for the future?

**Comment by totten** [comment]
@chriscroome Shell completion would be great. It doesn't exist - mostly because I don't know the protocol. However, [this library](https://github.com/stecman/symfony-console-completion) seems to provide some support (without needing to learn the protocol..?).

I'm not sure if I have time to do flesh it out, but here's a quick/experimental stab at #165. If that seems OK, then it's patch-welcome for further tuning.

**Comment by chriscroome** [comment]
Sorry I didn't look at this sooner @totten I have now tested it and it's great :slightly_smiling_face: I've added installing it to a [cv Ansible role I've written](https://galaxy.ansible.com/chriscroome/cv), thanks!
