### ISSUE TITLE
Best way to interact with database with cv?

### ISSUE THREAD

**Issue by herbdool** [civicrm/cv#20]
It appears that so far it might mean using the `cv cli`--not sure how. Are there plans to implement sql commands in cv? Like `cv sql-dump`, `cv sql-query`, `cv sql-connect` and so on?

Thanks for the useful tool!

**Comment by totten** [comment]
@herbdool Thanks for the comment; apologies for not spotting it before.

Right, `cv cli` is a REPL for running PHP. For SQL, we'd have to do another subcommand. FWIW, I haven't needed it because I usually have `drush` or `amp`. However, one could port over these commands:

 * https://github.com/amp-cli/amp/blob/master/src/Amp/Command/SqlCommand.php
 * https://github.com/amp-cli/amp/blob/master/src/Amp/Command/SqlDumpCommand.php
 * https://github.com/amp-cli/amp/blob/0.4.4/src/Amp/Database/Datasource.php#L136

The main change -- instead of [using the `instances` service to locate a data source](https://github.com/amp-cli/amp/blob/0.4.4/src/Amp/Command/SqlCommand.php#L60-L75), one could use `CIVICRM_DSN` and `CIVICRM_UF_DSN`.

**Comment by totten** [comment]
It should be noted that a `cv sql` command was subsequently ported. It's generally the same as the `amp sql` command. It can be used for either:

* Launching the interactive `mysql` cli
* Piping in SQL statements (and including dynamic data, eg `@ENV[USERNAME]` or `#ENV[USERID]`)

I think there could value in introducing more commands (eg backup/restore), but we should probably separate issues for those.

**Comment by herbdool** [comment]
Thanks @totten. I saw this issue in the backlog https://github.com/civicrm/cv/issues/73 which I think is about the backup / sql dump command. Can continue on that one.
