### ISSUE TITLE
Cron example

### ISSUE THREAD

**Issue by brylie** [civicrm/cv#41]
The README doesn't mention how to use cv via cron. Please consider adding a specific example of using cv via cron, including how to specify the CiviCRM path.

**Comment by MegaphoneJon** [comment]
The example would be  `cv api Job.execute --cwd <pathname>`, where <pathname> is the path to anywhere in your webroot (doesn't need to be civiroot).  Note that you need the latest version of cv (0.2.4) to use `--cwd`.

I looked for an obvious place to put this in the README, but it seems like the better place is in the [cron docs](https://docs.civicrm.org/sysadmin/en/latest/setup/jobs/#cv) - which specifies how to use cv for cron but not the path (since that's new).

**Comment by brylie** [comment]
Ah, thanks for pointing me to the cron docs.

**Comment by brylie** [comment]
OK, yeah. That is where I learned about CV, but couldn't figure out how to specify the working directory path.
