### ISSUE TITLE
despite specifying the target db for a new CiviCRM installation, cv uses the default CMS db

### ISSUE THREAD

**Issue by Upperholme** [civicrm/cv#99]
I'm trying to install Civi 5.37.2 into a fresh Drupal 9 installation (9.1.8), and I'm following the guide at https://docs.civicrm.org/installation/en/latest/general/cli-cv/ which details how I can specify a separate database for the Civi install, which is my preferred approach.
So I've added --db="mysql://dbuser:password@localhost:3306/dbname” onto my cv command as specified in the guide.
when I run the command this appears to be ignored. cv reports that is is creating civicrm_* database tables in the Drupal db. 
Am I missing something obvious or  is cv not doing its job properly?

**Comment by Upperholme** [comment]
Should have said that I'm running version 0.3.7 of cv

**Comment by totten** [comment]
Related chat on MM is https://chat.civicrm.org/civicrm/pl/of8thg4if7gydcid55ot9ujhmw

**Comment by totten** [comment]
Added an observation at the end of that chat -- I just want to make sure it doesn't get lost. There seems to be a typo in the form of the double-quote. ([There are at least three forms of double-quotes - straight, left, and right](https://stackoverflow.com/questions/18735921/are-there-different-types-of-double-quotes-in-utf-8-php-str-replace).)

Bash commands should always be written with straight/non-angled quotes (ASCII hex `0x22` or decimal `34`). But many tools (IIRC, Google Doc, MS Word, Mac Mail, ad nauseum) will auto-convert to angled-quotes. (Because... prettiness?) If one types/copies/pastes examples through one of these tools, they may munge the quoting.
